### ISSUE TITLE
Subtlety

### ISSUE THREAD

**Issue by ghost** [Phoenix0316/ColmarAcademy#2]
You could change the text color of the "start here button" to a color other than grey. This would help it appear on the site more clearly for viewers. Right now the text on the button blends in with the background color of the button

https://github.com/Phoenix0316/ColmarAcademy/blob/bfba371c5cb0434ced11e5f83f3492b296107b55/NewColmarSite.html#L51

**Comment by Phoenix0316** [comment]
I’ll get right on it.
